version: '3.8'

services:
  # MySQL Database
  salesapp-mysql:
    image: mysql:8.0
    container_name: salesapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: salesapp_user
      MYSQL_PASSWORD: salesapp_password
      MYSQL_DATABASE: salesapp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - salesapp-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Eureka Discovery Server
  eureka-discovery:
    build: ./eureka-discovery
    container_name: eureka-discovery
    ports:
      - "8761:8761"
    networks:
      - salesapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Config Service
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "8888:8888"
    depends_on:
      eureka-discovery:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-discovery:8761/eureka/
    networks:
      - salesapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8085:8085"
    depends_on:
      salesapp-mysql:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://salesapp-mysql:3306/salesapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-discovery:8761/eureka/
    networks:
      - salesapp-network

  # Client Service
  client-service:
    build: ./client-service
    container_name: client-service
    ports:
      - "8081:8081"
    depends_on:
      salesapp-mysql:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://salesapp-mysql:3306/salesapp_clients?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-discovery:8761/eureka/
    networks:
      - salesapp-network

  # Product Service
  produit-service:
    build: ./produit-service
    container_name: produit-service
    ports:
      - "8082:8082"
    depends_on:
      salesapp-mysql:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://salesapp-mysql:3306/salesapp_produits?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-discovery:8761/eureka/
    networks:
      - salesapp-network

  # Dispositif Service
  dispositif-service:
    build: ./dispositif-service
    container_name: dispositif-service
    ports:
      - "8484:8484"
    depends_on:
      salesapp-mysql:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://salesapp-mysql:3306/salesapp_dispositifs?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-discovery:8761/eureka/
    networks:
      - salesapp-network

  # Invoice (Facture) Service
  facture-service:
    build: ./facture-service
    container_name: facture-service
    ports:
      - "8383:8383"
    depends_on:
      salesapp-mysql:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://salesapp-mysql:3306/salesapp_factures?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-discovery:8761/eureka/
    networks:
      - salesapp-network

  # Payment (Reglement) Service
  reglement-service:
    build: ./reglement-service
    container_name: reglement-service
    ports:
      - "8282:8282"
    depends_on:
      salesapp-mysql:
        condition: service_healthy
      eureka-discovery:
        condition: service_healthy
      config-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://salesapp-mysql:3306/salesapp_reglements?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-discovery:8761/eureka/
    networks:
      - salesapp-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8181:8181"
    depends_on:
      eureka-discovery:
        condition: service_healthy
      config-service:
        condition: service_healthy
      auth-service:
        condition: service_started
      client-service:
        condition: service_started
      produit-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-discovery:8761/eureka/
    networks:
      - salesapp-network

  # Angular Frontend
  angular-frontend:
    build: ./angular-frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - salesapp-network

volumes:
  mysql_data:

networks:
  salesapp-network:
    driver: bridge