server:
  port: 8181

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/clients/**
          filters:
            - JwtAuthenticationFilter
        - id: produit-service
          uri: lb://produit-service
          predicates:
            - Path=/api/produits/**, /api/categories/**
          filters:
            - JwtAuthenticationFilter
        - id: dispositif-service
          uri: lb://dispositif-service
          predicates:
            - Path=/api/dispositifs/**
          filters:
            - JwtAuthenticationFilter
        - id: facture-service
          uri: lb://facture-service
          predicates:
            - Path=/api/factures/**
          filters:
            - JwtAuthenticationFilter
        - id: reglement-service
          uri: lb://reglement-service
          predicates:
            - Path=/api/reglements/**
          filters:
            - JwtAuthenticationFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: mySecretKey