export interface Facture {
  id?: number;
  numeroFacture: string;
  clientId: number;
  clientNom?: string;
  dateFacture: string;       // changed from Date to string
  dateEcheance?: string;     // changed from Date to string
  montantHT: number;
  montantTVA: number;
  montantTTC: number;
  tauxTVA: number;
  statut: string;
  lignes: any[];
  modePaiement?: string;
  observations?: string;
  dateCreation?: string;
  dateModification?: string;
}


export type StatutFacture =
  | 'BROUILLON'
  | 'VALIDEE'
  | 'ENVOYEE'
  | 'PAYEE'
  | 'ANNULEE'
  | 'EN_RETARD';

export interface LigneFacture {
  id?: number;                 // Optional because it's generated by the database
  dispositifId: number;        // corresponds to Long in Java, number in TS
  nomDispositif: string;
  quantite: number;            // corresponds to Integer in Java, number in TS
  prixUnitaire: number;        // corresponds to Double in Java, number in TS
  montantLigne: number;        // calculated as quantite * prixUnitaire in Java
  description?: string;        // optional field
  }
  