server:
  port: 8761

eureka:
  instance:
    hostname: eureka-discovery
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false   #  Disable self-preservation in dev
    eviction-interval-timer-in-ms: 10000  # Evict unresponsive instances every 10s

spring:
  application:
    name: eureka-discovery

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
